#ifndef DAGGER_PARAMS_H
#define DAGGER_PARAMS_H


/* Don't change anything below this line */
#define DAGGER_L 4
#define DAGGER_MU 6
#define DAGGER_ET 6

#define DAGGER_N 256

#define DAGGER_EP 9
#define DAGGER_P (1 << DAGGER_EP)

#define DAGGER_EQ 13
#define DAGGER_Q (1 << DAGGER_EQ)

#define DAGGER_SEEDBYTES 32
#define DAGGER_NOISESEEDBYTES 32
#define DAGGER_KEYBYTES 32
#define DAGGER_HASHBYTES 32

#define DAGGER_POLYCOINBYTES (DAGGER_MU * DAGGER_N / 8)

#define DAGGER_POLYBYTES (DAGGER_EQ * DAGGER_N / 8)
#define DAGGER_POLYVECBYTES (DAGGER_L * DAGGER_POLYBYTES)

#define DAGGER_POLYCOMPRESSEDBYTES (DAGGER_EP * DAGGER_N / 8)
#define DAGGER_POLYVECCOMPRESSEDBYTES (DAGGER_L * DAGGER_POLYCOMPRESSEDBYTES)

#define DAGGER_SCALEBYTES_KEM (DAGGER_ET * DAGGER_N / 8)

#define DAGGER_INDCPA_PUBLICKEYBYTES (DAGGER_POLYVECCOMPRESSEDBYTES + DAGGER_SEEDBYTES)
#define DAGGER_INDCPA_SECRETKEYBYTES (DAGGER_POLYVECBYTES)

#define DAGGER_PUBLICKEYBYTES (DAGGER_INDCPA_PUBLICKEYBYTES)
#define DAGGER_SECRETKEYBYTES (DAGGER_INDCPA_SECRETKEYBYTES + DAGGER_INDCPA_PUBLICKEYBYTES + DAGGER_HASHBYTES + DAGGER_KEYBYTES)

#define DAGGER_BYTES_CCA_DEC (DAGGER_POLYVECCOMPRESSEDBYTES + DAGGER_SCALEBYTES_KEM)

#endif
